### PR TITLE
Implementing Trash/Delete/ServiceAuth.

### PR DESCRIPTION
**Pull request by smeggingsmegger**
Adds the ability to use service auth in PyDrive as well as the trash and
delete methods.

### CODE REVIEW

**Comment by smeggingsmegger** [comment]
I signed it!

**Comment by smeggingsmegger** [comment]
Replaces: https://github.com/googledrive/PyDrive/pull/14

**Comment by smeggingsmegger** [comment]
@aliafshar @lawrencebenson this is the new PR that brings in the changes from before. I haven't had a chance to test it but it *looks* to be all the changes in their final form minus the PEP-8 changes. I went ahead and left those out because they should really be in their own PR if we decide to do them at all.

**Comment by RNabel** [comment]
@ccortezia Could you please sign the CLA so this can be merged.

**Comment by ccortezia** [comment]
@RNabel, it has been signed.

**Comment by RNabel** [comment]
Cool, just double-checked.

**Comment by RNabel** [comment]
Merged. I added tests for Trash/UnTrash/Delete, but not for the ServiceAuth code. It would be awesome if you could add tests for ServiceAuth. 
@smeggingsmegger and @ccortezia thank you for working on this!

**Pull request merged**
