### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by pferate**
Upgrading code-base to work in Python 2 and 3 (tested with 2.6, 2.7, 3.3, 3.4).

### CODE REVIEW

**Comment by pferate** [comment]
Hi @aliafshar and @rakyll, any chance for a code review on this PR or any other update?  I also have PR #44, which adds tox.

**Comment by aliafshar** [comment]
Thanks for this. I can merge once I have a signed CLA.

**Comment by pferate** [comment]
Is this different than the one for oauth2client and google-api-python-client? I have a CLA on file for those.

**Comment by aliafshar** [comment]
Thanks.

**Comment by AlfioEmanueleFresta** [comment]
@aliafshar any chance this can be pushed to PyPy?

**Pull request merged**
