### PR TITLE
Add method to return Google Drive information

### PR DESCRIPTION
**Pull request by hschauhan**
A method is added to drive.py to return the Google Drive's
information pointed by its auth instance. The return value
is a dictionary containing Google Drive information like,
logged user, current usage, total quota, etc.

Signed-off-by: Himanshu Chauhan <hschauhan@nulltrace.org>

### CODE REVIEW

**Comment by aliafshar** [comment]
Hi, I can merge this once you have signed the CLA. Thanks.

**Comment by v1k45** [comment]
Is this PR ever going to be merged? :confused:  @aliafshar @hschauhan

**Comment by hschauhan** [comment]
I signed it!

**Comment by hschauhan** [comment]
@aliafshar please merge the PR.

**Pull request merged**
