### PR TITLE
Adding PEP8, Trash, Delete, and ServiceAuth

### PR DESCRIPTION
**Pull request by smeggingsmegger**
This PR contains the following improvements:

* Conforms to PEP-8 formatting
* Trash, UnTrash methods added
* Delete method added
* Support for ServiceAuth
* New test for ServiceAuth

### CODE REVIEW

**Comment by subhonjon** [comment]
I proposed a few docs related tweaks. Otherwise LGTM. Thanks for working on this.

**Comment by aliafshar** [comment]
Arg, this is my fault for not merging this before. Sorry. It needs updating now and I appreciate if you don't want to after putting in the hard work. Anyway, sorry.

**Comment by lawrencebenson** [comment]
@smeggingsmegger is it possible that you could update yout stuff for it to be merged? I could really use the trash and delete functions. if you dont feel like it, i can bring the PR up to date but i would hate to take the credit for your work, so please let me know

**Comment by smeggingsmegger** [comment]
@aliafshar @lawrencebenson I'll fix the PR. It looks like we have so many conflicts because of the PEP8 commit. I might rebase that one out and see how that goes.

**Comment by lawrencebenson** [comment]
@smeggingsmegger any news on the pr?

**Comment by smeggingsmegger** [comment]
I finally have time to work on this. I should have an updated or new PR very soon. It's likely I am going to remove the PEP8 conversion for the time being and just add the Trash_and_Delete changes standalone.

**Comment by smeggingsmegger** [comment]
Closing this and re-opening it with a different branch.

**Pull request closed without merging**
