### PR TITLE
Update to Drive V3

### PR DESCRIPTION
**Pull request by sqrrrl**

### CODE REVIEW

**Comment by Scoppio** [comment]
your test_file do not work. It gives an exception in the level of the http\client.py saying that latin-1 cannot be encoded because a character /ufffd is out of 255 range.

**Comment by sqrrrl** [comment]
Hmm, not getting any encoding issues on my end. What OS/Python version?

**Comment by cpb8010** [comment]
I had the same error when uploading certain files. The tracebacks look like:
```
    report_file.Upload()
  File "C:\Users\sa\Anaconda3\lib\site-packages\pydrive\files.py", line 225, in Upload
    self._FilesInsert(param=param)
  File "C:\Users\sa\Anaconda3\lib\site-packages\pydrive\auth.py", line 55, in _decorated
    return decoratee(self, *args, **kwargs)
  File "C:\Users\sa\Anaconda3\lib\site-packages\pydrive\files.py", line 241, in _FilesInsert
    metadata = self.auth.service.files().insert(**param).execute()
  File "C:\Users\sa\Anaconda3\lib\site-packages\oauth2client\util.py", line 142, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\sa\Anaconda3\lib\site-packages\googleapiclient\http.py", line 722, in execute
    body=self.body, headers=self.headers)
  File "C:\Users\sa\Anaconda3\lib\site-packages\oauth2client\client.py", line 589, in new_request
    redirections, connection_type)
  File "C:\Users\sa\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Users\sa\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\sa\Anaconda3\lib\site-packages\httplib2\__init__.py", line 988, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "C:\Users\sa\Anaconda3\lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\sa\Anaconda3\lib\http\client.py", line 1125, in _send_request
    body = body.encode('iso-8859-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 766-768: ordinal not in range(256)
```
It might be a problem with a dependency. I got the current version of pydrive from pip and then applied your patch. I didn't see any changes in the package metadata so I assumed it would just drop in.

Windows Server 2012 R2 Datacenter
Python 3.4.3 (64-bit)

**Comment by sqrrrl** [comment]
I think this is related to https://github.com/google/google-api-python-client/issues/145 and is an issue with the client library (fixed, pending new release.)

As mentioned previously, I wasn't able to reproduce. I'm using Python 2.7.

**Comment by RNabel** [comment]
@sqrrrl Since this is going to break back-wards compatibility, this could be combined with a refactor to comply with PEP8 (or [Google's Python](https://google.github.io/styleguide/pyguide.html) style guide). Thoughts?

**Pull request closed without merging**
